Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.network :forwarded_port, guest: 8888, host: 8111
  config.vm.synced_folder "../sample_images", "/images"
  config.vm.provider :virtualbox do |v, _|
    v.memory = 1024
  end
  config.vm.provision :shell, inline: <<-SHELL
    sudo date > /etc/vagrant_provisioned_at
    apt-get update
    apt-get upgrade
    apt-get -y -q install git-core cmake g++ zlib1g-dev libtiff5-dev imagemagick libmagickwand-dev libopenjp2-7 libopenjp2-7-dev golang gb
  SHELL
  config.vm.provision :shell, path: 'openjpeg.sh'
  config.vm.provision :shell, path: 'rais.sh'
end